/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package httye;

/**
 *
 * @author Ramdani
 */
public class Find extends javax.swing.JFrame {

    /**
     * Creates new form Find
     */
    public Find() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tScoreFind = new javax.swing.JLabel();
        lvl1G2 = new javax.swing.JLabel();
        b1L1G2 = new javax.swing.JLabel();
        b2L1G2 = new javax.swing.JLabel();
        b3L1G2 = new javax.swing.JLabel();
        btnL1G1 = new javax.swing.JLabel();
        lvl2G2 = new javax.swing.JLabel();
        b1L2G2 = new javax.swing.JLabel();
        b2L2G2 = new javax.swing.JLabel();
        b3L2G2 = new javax.swing.JLabel();
        btnL2G1 = new javax.swing.JLabel();
        lvl3G1 = new javax.swing.JLabel();
        b1L3G2 = new javax.swing.JLabel();
        b2L3G2 = new javax.swing.JLabel();
        b3L3G2 = new javax.swing.JLabel();
        btnL3G1 = new javax.swing.JLabel();
        lvl4G2 = new javax.swing.JLabel();
        b1L4G2 = new javax.swing.JLabel();
        b2L4G2 = new javax.swing.JLabel();
        b3L4G2 = new javax.swing.JLabel();
        btnL4G1 = new javax.swing.JLabel();
        lvl5G2 = new javax.swing.JLabel();
        b1L5G2 = new javax.swing.JLabel();
        b2L5G2 = new javax.swing.JLabel();
        b3L5G2 = new javax.swing.JLabel();
        btnL5G1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backF = new javax.swing.JLabel();
        homeF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(130, 207, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\kacamata3.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 140));

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("F I N D");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel3.setText("/30");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        tScoreFind.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        tScoreFind.setText("0");
        jPanel1.add(tScoreFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 20, 30));

        lvl1G2.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        lvl1G2.setForeground(new java.awt.Color(255, 255, 255));
        lvl1G2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvl1G2.setText("LEVEL 1");
        jPanel1.add(lvl1G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 160, 30));

        b1L1G2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Kuliah/Semester 5/Praktikum/Pemrograman Berorientasi Objek/Project Akhir/Desain/Images/starBlack.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(b1L1G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 270, -1, -1));

        b2L1G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b2L1G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 270, -1, -1));

        b3L1G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b3L1G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 270, -1, -1));

        btnL1G1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel1.add(btnL1G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 70));

        lvl2G2.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        lvl2G2.setForeground(new java.awt.Color(255, 255, 255));
        lvl2G2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvl2G2.setText("LEVEL 2");
        jPanel1.add(lvl2G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 30));

        b1L2G2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Kuliah/Semester 5/Praktikum/Pemrograman Berorientasi Objek/Project Akhir/Desain/Images/starBlack.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(b1L2G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        b2L2G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b2L2G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        b3L2G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b3L2G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        btnL2G1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel1.add(btnL2G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, 70));

        lvl3G1.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        lvl3G1.setForeground(new java.awt.Color(255, 255, 255));
        lvl3G1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvl3G1.setText("LEVEL 3");
        jPanel1.add(lvl3G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 30));

        b1L3G2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Kuliah/Semester 5/Praktikum/Pemrograman Berorientasi Objek/Project Akhir/Desain/Images/starBlack.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(b1L3G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        b2L3G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b2L3G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        b3L3G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b3L3G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        btnL3G1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel1.add(btnL3G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, 70));

        lvl4G2.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        lvl4G2.setForeground(new java.awt.Color(255, 255, 255));
        lvl4G2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvl4G2.setText("LEVEL 4");
        jPanel1.add(lvl4G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 160, 30));

        b1L4G2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Kuliah/Semester 5/Praktikum/Pemrograman Berorientasi Objek/Project Akhir/Desain/Images/starBlack.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(b1L4G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        b2L4G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b2L4G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        b3L4G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b3L4G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        btnL4G1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel1.add(btnL4G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, 70));

        lvl5G2.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        lvl5G2.setForeground(new java.awt.Color(255, 255, 255));
        lvl5G2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvl5G2.setText("LEVEL 5");
        jPanel1.add(lvl5G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 160, 30));

        b1L5G2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Kuliah/Semester 5/Praktikum/Pemrograman Berorientasi Objek/Project Akhir/Desain/Images/starBlack.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(b1L5G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        b2L5G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b2L5G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        b3L5G2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\starBlack.png")); // NOI18N
        jPanel1.add(b3L5G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        btnL5G1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel1.add(btnL5G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\star.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        backF.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\back.png")); // NOI18N
        jPanel1.add(backF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        homeF.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Kuliah/Semester 5/Praktikum/Pemrograman Berorientasi Objek/Project Akhir/Desain/Images/home2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(homeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Find().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1L1G2;
    private javax.swing.JLabel b1L2G2;
    private javax.swing.JLabel b1L3G2;
    private javax.swing.JLabel b1L4G2;
    private javax.swing.JLabel b1L5G2;
    private javax.swing.JLabel b2L1G2;
    private javax.swing.JLabel b2L2G2;
    private javax.swing.JLabel b2L3G2;
    private javax.swing.JLabel b2L4G2;
    private javax.swing.JLabel b2L5G2;
    private javax.swing.JLabel b3L1G2;
    private javax.swing.JLabel b3L2G2;
    private javax.swing.JLabel b3L3G2;
    private javax.swing.JLabel b3L4G2;
    private javax.swing.JLabel b3L5G2;
    private javax.swing.JLabel backF;
    private javax.swing.JLabel btnL1G1;
    private javax.swing.JLabel btnL2G1;
    private javax.swing.JLabel btnL3G1;
    private javax.swing.JLabel btnL4G1;
    private javax.swing.JLabel btnL5G1;
    private javax.swing.JLabel homeF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lvl1G2;
    private javax.swing.JLabel lvl2G2;
    private javax.swing.JLabel lvl3G1;
    private javax.swing.JLabel lvl4G2;
    private javax.swing.JLabel lvl5G2;
    private javax.swing.JLabel tScoreFind;
    // End of variables declaration//GEN-END:variables
}
