/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package httye;

/**
 *
 * @author Ramdani
 */
public class List_Games extends javax.swing.JFrame {
    
    /**
     * Creates new form List_Games
     */
    public List_Games() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numBer = new javax.swing.JLabel();
        btnNumber = new javax.swing.JLabel();
        fiNd = new javax.swing.JLabel();
        btnFind = new javax.swing.JLabel();
        backToHome = new javax.swing.JLabel();
        pilihGame = new javax.swing.JLabel();
        kacaPembesar = new javax.swing.JLabel();
        kacamata2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(130, 207, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numBer.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        numBer.setForeground(new java.awt.Color(255, 255, 255));
        numBer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numBer.setText("N U M B E R");
        numBer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numBerMouseClicked(evt);
            }
        });
        jPanel1.add(numBer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 160, 60));

        btnNumber.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel1.add(btnNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, 70));

        fiNd.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        fiNd.setForeground(new java.awt.Color(255, 255, 255));
        fiNd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiNd.setText("F I N D");
        fiNd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiNdMouseClicked(evt);
            }
        });
        jPanel1.add(fiNd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 160, 60));

        btnFind.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel1.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, 70));

        backToHome.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\back.png")); // NOI18N
        backToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToHomeMouseClicked(evt);
            }
        });
        jPanel1.add(backToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        pilihGame.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        pilihGame.setText("CHOOSE A GAME");
        jPanel1.add(pilihGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        kacaPembesar.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\kacaPembesar.png")); // NOI18N
        jPanel1.add(kacaPembesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 130, 110));

        kacamata2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\kacamata2.png")); // NOI18N
        jPanel1.add(kacamata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToHomeMouseClicked
        // TODO add your handling code here:
        HTTYE.lg.setVisible(false);
        HTTYE.mu.setVisible(true);
    }//GEN-LAST:event_backToHomeMouseClicked

    private void numBerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numBerMouseClicked
        // TODO add your handling code here:
        HTTYE.lg.setVisible(false);
        HTTYE.num.setVisible(true);
    }//GEN-LAST:event_numBerMouseClicked

    private void fiNdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiNdMouseClicked
        // TODO add your handling code here:
        HTTYE.lg.setVisible(false);
        HTTYE.fin.setVisible(true);
    }//GEN-LAST:event_fiNdMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(List_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(List_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(List_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(List_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new List_Games().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backToHome;
    private javax.swing.JLabel btnFind;
    private javax.swing.JLabel btnNumber;
    private javax.swing.JLabel fiNd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kacaPembesar;
    private javax.swing.JLabel kacamata2;
    private javax.swing.JLabel numBer;
    private javax.swing.JLabel pilihGame;
    // End of variables declaration//GEN-END:variables
}
