/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package httye;

import javax.swing.*;

/**
 *
 * @author Ramdani
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kacamata = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        conTinue = new javax.swing.JLabel();
        btnContinue = new javax.swing.JLabel();
        newGame = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        heLp = new javax.swing.JLabel();
        btnHelp = new javax.swing.JLabel();
        quIt = new javax.swing.JLabel();
        btnQuit = new javax.swing.JLabel();
        teropong = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(130, 207, 237));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kacamata.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\kacamata.png")); // NOI18N
        jPanel2.add(kacamata, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 80));

        judul.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        judul.setText("HOW TO TRAIN YOUR EYES");
        jPanel2.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        conTinue.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        conTinue.setForeground(new java.awt.Color(255, 255, 255));
        conTinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conTinue.setText("C O N T I N U E");
        conTinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conTinueMouseClicked(evt);
            }
        });
        jPanel2.add(conTinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 160, 60));

        btnContinue.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel2.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 70));

        newGame.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        newGame.setForeground(new java.awt.Color(255, 255, 255));
        newGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGame.setText("N E W  G A M E");
        newGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameMouseClicked(evt);
            }
        });
        jPanel2.add(newGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 160, 60));

        btnNewGame.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel2.add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 70));

        about.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about.setText("A  B  O  U  T");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jPanel2.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 160, 60));

        btnAbout.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel2.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, 70));

        heLp.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        heLp.setForeground(new java.awt.Color(255, 255, 255));
        heLp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heLp.setText("H  E  L  P");
        heLp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heLpMouseClicked(evt);
            }
        });
        jPanel2.add(heLp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 160, 60));

        btnHelp.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel2.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, 70));

        quIt.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        quIt.setForeground(new java.awt.Color(255, 255, 255));
        quIt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quIt.setText("Q  U  I  T");
        quIt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quItMouseClicked(evt);
            }
        });
        jPanel2.add(quIt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 160, 60));

        btnQuit.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\button.png")); // NOI18N
        jPanel2.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, 70));

        teropong.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Praktikum\\Pemrograman Berorientasi Objek\\Project Akhir\\Desain\\Images\\teropong.png")); // NOI18N
        jPanel2.add(teropong, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conTinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conTinueMouseClicked
        // TODO add your handling code here:
        HTTYE.mu.setVisible(false);
        HTTYE.lg.setVisible(true);
        
    }//GEN-LAST:event_conTinueMouseClicked

    private void newGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameMouseClicked
        // TODO add your handling code here:
        HTTYE.mu.setVisible(false);
        HTTYE.lg.setVisible(true);
    }//GEN-LAST:event_newGameMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        HTTYE.mu.setVisible(false);
        HTTYE.ab.setVisible(true);
    }//GEN-LAST:event_aboutMouseClicked

    private void heLpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heLpMouseClicked
        // TODO add your handling code here:
        HTTYE.mu.setVisible(false);
        HTTYE.hl.setVisible(true);
    }//GEN-LAST:event_heLpMouseClicked

    private void quItMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quItMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quItMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//////                Menu_Utama mu = Menu_Utama().setVisible(true);
////                new Menu_Utama().setVisible(true);
//                JFrame.setWindowDecorationStyle(JRootPane.NONE);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnContinue;
    private javax.swing.JLabel btnHelp;
    private javax.swing.JLabel btnNewGame;
    private javax.swing.JLabel btnQuit;
    private javax.swing.JLabel conTinue;
    private javax.swing.JLabel heLp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel kacamata;
    private javax.swing.JLabel newGame;
    private javax.swing.JLabel quIt;
    private javax.swing.JLabel teropong;
    // End of variables declaration//GEN-END:variables
}
